title: Kendall Ruth # your name (or website title) here
logo: "/images/Headshot.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Expert in baseball analytics, player performance analysis, predictive modeling, and data visualization. Provided real-time insights to optimize training and decision-making.
  <br><br>
  Proficient in Python, R, and SQL, with experience using Power BI and Tableau to create dashboards and predictive models. Authored articles on player development and utilized R Shiny for real-time data applications.
  <br><br>
  <a href="https://www.linkedin.com/in/kendallruth99/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
